schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "Colorista"
version = "1.0.0"
name = "Colorista"
tagline = "Colorista"
maintainer = "AIGODLIKE <karrycharon@qq.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/AIGODLIKE/Colorista"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Modeling", "Node", "Render", "Compositing"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
[permissions]
files = "Read Node"