schema_version = "1.0.0"

id = "Colorista"
version = "1.2.2"
name = "Colorista"
tagline = "A convenient color grading add-on designed for colorists"
maintainer = "AIGODLIKE <karrycharon@qq.com>"
type = "add-on"

website = "https://github.com/AIGODLIKE/Colorista"
support = "https://github.com/AIGODLIKE/Colorista/issues"

tags = ["Compositing", "Node"]

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
  "SPDX:CC0-1.0",
]
copyright = [
  "2024-2026 AIGODLIKE",
]

[permissions]
files = "Import compositor presets and cache files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.idea/",
  "/utils/logs/",
  "/resource/cache/",
  "/resource/CN/default/default/",
  "/utils/timeit.py",
  "/*.zip",
]
